workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-32
    acceleratorType: NVIDIA_TESLA_P100
    acceleratorCount: 2
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/irn-71028-lab-a6/robocar/robocar-gcp-trainer:latest
